version: '3.7'

services:
  server:
    container_name: woodongdang
    build: .
    ports:
      - '80:80'
    networks:
      - backend

  mongodb:
    container_name: mongo
    image: mvertes/alpine-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo:
